using CsMesh.Analysis;
using CsMesh.Models;
using Xunit;

namespace CsMesh.Tests;

/// <summary>
/// Generators other than Razor write their output to obj/{config}/{tfm}/generated/ too, but the
/// indexer used to look only for *_razor.g.cs / *_cshtml.g.cs under a RazorSourceGenerator segment
/// and silently dropped everything else. The visible cost was a JsonSerializerContext whose
/// generated half -- its "Default" instance and its serialization methods -- never entered the
/// graph, so every call through it came out unresolved.
///
/// These fixtures write the shape a source generator produces by hand rather than running one, so
/// the suite neither builds nor depends on an analyzer package. The shape is the real one: a
/// partial class completed by a .g.cs under obj/Debug/net10.0/generated/&lt;generator&gt;/.
/// </summary>
public sealed class GeneratedSourceIngestionTests : IDisposable
{
    private readonly string _root;

    public GeneratedSourceIngestionTests()
    {
        _root = Path.Combine(Path.GetTempPath(), "csmesh-generated-" + Guid.NewGuid().ToString("N")[..8]);
        Directory.CreateDirectory(_root);

        Write("App.csproj",
            "<Project Sdk=\"Microsoft.NET.Sdk\"><PropertyGroup><TargetFramework>net10.0</TargetFramework></PropertyGroup></Project>");

        // The source half of the partial. Without the generated half, ThingContext.Default is
        // unbound: the class is only half declared, and the call through it cannot resolve.
        Write("Ctx.cs", """
            using System.Text.Json.Serialization;

            namespace TestApp
            {
                public class Thing { public int Id { get; set; } }

                internal partial class ThingContext : JsonSerializerContext;

                public class Caller
                {
                    public string Go(Thing t) => ThingContext.Default.Serialize(t);
                }
            }
            """);
    }

    public void Dispose()
    {
        try { Directory.Delete(_root, recursive: true); } catch { /* temp dir */ }
    }

    private void Write(string relative, string content)
    {
        var path = Path.Combine(_root, relative.Replace('/', Path.DirectorySeparatorChar));
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        File.WriteAllText(path, content);
    }

    /// <summary>
    /// The generated half. The directory name is deliberately not RazorSourceGenerator and the file
    /// name has no _razor/_cshtml suffix, which is exactly what the old filter keyed on.
    /// </summary>
    private void WriteGeneratedContext(string config = "Debug", string tfm = "net10.0")
    {
        var generatedDir = Path.Combine(_root, "obj", config, tfm, "generated",
            "System.Text.Json.SourceGeneration", "System.Text.Json.SourceGeneration.JsonSourceGenerator");
        Directory.CreateDirectory(generatedDir);

        File.WriteAllText(Path.Combine(generatedDir, "ThingContext.g.cs"), """
            // <auto-generated/>
            #nullable enable annotations
            namespace TestApp
            {
                internal partial class ThingContext
                {
                    private ThingContext() : base(null) { }

                    public static ThingContext Default { get; } = new ThingContext();

                    public string Serialize(Thing t) => "";

                    protected override global::System.Text.Json.JsonSerializerOptions? GeneratedSerializerOptions => null;

                    public override global::System.Text.Json.Serialization.Metadata.JsonTypeInfo? GetTypeInfo(global::System.Type type) => null;
                }
            }
            """);
    }

    [Fact]
    public void GeneratedOutputPresent_CompletesThePartialAndBindsTheGeneratedMember()
    {
        WriteGeneratedContext();

        var graph = Indexer.Build(_root);
        graph.Freeze();

        Assert.Equal(1, graph.GeneratedSourcesIndexed);

        // The generated "Default" instance is the member the calls resolve through.
        Assert.Contains(graph.Nodes, n => n.Short == "ThingContext.Default");

        Assert.DoesNotContain(graph.Unresolved, u => u.Reason == "no-candidate-symbol");
        Assert.Equal(0, graph.UnresolvedCallSites);
    }

    [Fact]
    public void GeneratedOutputAbsent_LeavesTheMemberUnboundAndReportsTheCall()
    {
        var graph = Indexer.Build(_root);
        graph.Freeze();

        Assert.Equal(0, graph.GeneratedSourcesIndexed);

        // Not silently dropped: the call through the missing generated member is on the record.
        var unresolved = Assert.Single(graph.Unresolved, u =>
            u.Kind == "call" && u.Reason == "no-candidate-symbol" && u.Expression.Contains("Serialize"));
        Assert.Equal("call", unresolved.Kind);
        Assert.True(graph.UnresolvedCallSites >= 1);
    }

    /// <summary>
    /// Debug and Release both hold a copy of every generated type. Only the newest generated
    /// directory is read, so the type cannot arrive twice and produce CS0101 across the graph.
    /// </summary>
    [Fact]
    public void DebugAndReleaseBothPresent_IndexesOneCopy()
    {
        WriteGeneratedContext("Debug", "net10.0");
        WriteGeneratedContext("Release", "net10.0");

        var graph = Indexer.Build(_root);
        graph.Freeze();

        Assert.Equal(1, graph.GeneratedSourcesIndexed);
        Assert.Single(graph.Nodes, n => n.Short == "ThingContext.Default");
    }
}
