using System.Text;
using CsMesh.Analysis;
using CsMesh.Commands;
using CsMesh.Common;
using CsMesh.Models;
using CsMesh.Storage;
using Xunit;

namespace CsMesh.Tests;

/// <summary>
/// Modern Razor compiles through a Roslyn source generator whose output normally lives only in
/// memory -- a plain 'dotnet build' of a fresh Blazor project writes zero *.razor.g.cs files to
/// disk. Generated sources only appear on disk when a build ran with both
/// -p:EmitCompilerGeneratedFiles=true and --no-incremental, and even then under a name like
/// Counter_razor.g.cs rather than Counter.razor.g.cs.
///
/// This fixture writes that shape by hand rather than invoking a real build, so the test suite
/// does not depend on the .NET SDK's Razor tooling or network access. The shape itself -- the
/// #pragma checksum line, the fully qualified RouteAttribute, the obj/{config}/{tfm}/generated/...
/// directory nesting -- was checked against a real 'dotnet new blazor' project built both ways.
/// </summary>
public sealed class RazorComponentIndexingTests : IDisposable
{
    private readonly string _root;

    public RazorComponentIndexingTests()
    {
        _root = Path.Combine(Path.GetTempPath(), "csmesh-razor-" + Guid.NewGuid().ToString("N")[..8]);
        Directory.CreateDirectory(Path.Combine(_root, "Pages"));
        Directory.CreateDirectory(Path.Combine(_root, "Services"));

        Write("App.csproj",
            "<Project Sdk=\"Microsoft.NET.Sdk.Web\"><PropertyGroup><TargetFramework>net10.0</TargetFramework></PropertyGroup></Project>");

        Write("Services/CounterService.cs", """
            namespace TestApp.Services
            {
                public class CounterService
                {
                    public void Increment() { }
                }
            }
            """);

        // Never parsed directly -- only counted, and named by the checksum line in the generated
        // file below. Its content does not need to be valid Razor for that.
        Write("Pages/Counter.razor", "<h1>@currentCount</h1>\n@code { private int currentCount; }");

        WriteGeneratedComponent();

        Graph = Indexer.Build(_root);
        Graph.Freeze();
    }

    public Graph Graph { get; private set; }

    private string RazorAbsolutePath => Path.Combine(_root, "Pages", "Counter.razor");

    private void Write(string relative, string content)
    {
        var path = Path.Combine(_root, relative.Replace('/', Path.DirectorySeparatorChar));
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        File.WriteAllText(path, content);
    }

    /// <summary>
    /// The shape a real 'dotnet build --no-incremental -p:EmitCompilerGeneratedFiles=true' writes:
    /// a checksum line naming the .razor file, a fully qualified RouteAttribute (generated code
    /// never carries a using for it), and a partial class whose @code method calls a service.
    /// </summary>
    private void WriteGeneratedComponent()
    {
        var generatedDir = Path.Combine(_root, "obj", "Debug", "net10.0", "generated",
            "Microsoft.CodeAnalysis.Razor.Compiler",
            "Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator", "Pages");
        Directory.CreateDirectory(generatedDir);

        var razorPath = RazorAbsolutePath.Replace('\\', '/');
        var text = $$"""
            #pragma checksum "{{razorPath}}" "{ff1816ec-aa5e-4d10-87f6-980198115c8b}" "0000"
            // <auto-generated/>
            #pragma warning disable 1591
            namespace TestApp.Pages
            {
                #line default
                using global::System;
                using global::System.Threading.Tasks;
                using global::TestApp.Services;

                [global::Microsoft.AspNetCore.Components.RouteAttribute("/counter")]
                public partial class Counter : global::Microsoft.AspNetCore.Components.ComponentBase
                {
                    private readonly CounterService _service = new CounterService();

                    private void IncrementCount()
                    {
                        _service.Increment();
                    }
                }
            }
            #pragma warning restore 1591
            """;

        File.WriteAllText(Path.Combine(generatedDir, "Counter_razor.g.cs"), text);
    }

    private Node Node(string name) =>
        Graph.Nodes.FirstOrDefault(n => n.Name == name)
        ?? throw new InvalidOperationException($"no node named '{name}'. Have: " +
                                               string.Join(", ", Graph.Nodes.Select(n => n.Name).Take(60)));

    [Fact]
    public void GeneratedComponentsAreCountedAsIndexed()
    {
        Assert.Equal(1, Graph.RazorFileCount);
        Assert.Equal(1, Graph.RazorComponentsIndexed);
    }

    [Fact]
    public void TheComponentTypeIsTaggedRazorComponent()
    {
        Assert.Contains("razor-component", Node("TestApp.Pages.Counter").Tags);
    }

    /// <summary>Same tag shape TryMinimalApiRoute uses, so entrypoints and blast-radius need no new rule.</summary>
    [Fact]
    public void TheAtPageRouteBecomesAnHttpEntrypointTag()
    {
        var tags = Node("TestApp.Pages.Counter").Tags;
        Assert.Contains("http:GET /counter", tags);
        Assert.Contains(tags, t => t.StartsWith("http:", StringComparison.Ordinal));
    }

    /// <summary>
    /// The failure this exists to prevent: a user told to open an obj/ path that a clean deletes.
    /// </summary>
    [Fact]
    public void TheComponentNodeFileIsTheRazorSourceNotTheGeneratedFile()
    {
        var file = Node("TestApp.Pages.Counter").File;

        Assert.Equal(Path.Combine("Pages", "Counter.razor"), file);
        Assert.DoesNotContain("obj", file.Split(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar));
        Assert.DoesNotContain("_razor.g.cs", file, StringComparison.Ordinal);
    }

    /// <summary>
    /// What blast-radius and 'who calls this' actually depend on: a real Call edge from the
    /// component's @code method to the service it uses, not merely the component's own presence.
    /// </summary>
    [Fact]
    public void AComponentMethodCallingAServiceProducesACallEdge()
    {
        var method = Node("TestApp.Pages.Counter.IncrementCount");
        var service = Node("TestApp.Services.CounterService.Increment");

        Assert.Contains(Graph.Edges, e => e.From == method.Id && e.To == service.Id && e.Kind == EdgeKind.Call);
    }

    public void Dispose()
    {
        try { Directory.Delete(_root, recursive: true); } catch { /* temp dir */ }
    }
}

/// <summary>
/// The default case: no build ever ran with -p:EmitCompilerGeneratedFiles=true, so obj/ holds
/// nothing this indexer can read. Everything else in the repository must still index normally.
/// </summary>
public sealed class RazorWithoutGeneratedOutputTests : IDisposable
{
    private readonly string _root;

    public RazorWithoutGeneratedOutputTests()
    {
        _root = Path.Combine(Path.GetTempPath(), "csmesh-razor-nogen-" + Guid.NewGuid().ToString("N")[..8]);
        Directory.CreateDirectory(Path.Combine(_root, "Pages"));
        Directory.CreateDirectory(Path.Combine(_root, "Services"));

        Write("App.csproj",
            "<Project Sdk=\"Microsoft.NET.Sdk.Web\"><PropertyGroup><TargetFramework>net10.0</TargetFramework></PropertyGroup></Project>");
        Write("Services/CounterService.cs", """
            namespace TestApp.Services
            {
                public class CounterService { public void Increment() { } }
            }
            """);
        Write("Pages/Counter.razor", "<h1>@currentCount</h1>\n@code { private int currentCount; }");
    }

    private void Write(string relative, string content)
    {
        var path = Path.Combine(_root, relative.Replace('/', Path.DirectorySeparatorChar));
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        File.WriteAllText(path, content);
    }

    [Fact]
    public void IndexingDoesNotCrashAndReportsNothingIndexed()
    {
        var graph = Indexer.Build(_root);

        Assert.Equal(1, graph.RazorFileCount);
        Assert.Equal(0, graph.RazorComponentsIndexed);
    }

    /// <summary>No false edges: ordinary C# in the same repository indexes exactly as if Razor were absent.</summary>
    [Fact]
    public void OrdinaryCodeInTheSameRepositoryStillIndexes()
    {
        var graph = Indexer.Build(_root);

        Assert.Contains(graph.Nodes, n => n.Name == "TestApp.Services.CounterService.Increment");
        Assert.DoesNotContain(graph.Nodes, n => n.Tags.Contains("razor-component"));
    }

    public void Dispose()
    {
        try { Directory.Delete(_root, recursive: true); } catch { /* temp dir */ }
    }
}

/// <summary>
/// A dirty .razor file cannot be rebound incrementally: its node came from the generated C# a
/// build produced, and that generated C# will not change until the next build runs. Rebinding
/// against stale generated text would silently mismatch the edited .razor file.
/// </summary>
public sealed class RazorIncrementalDeclineTests : IDisposable
{
    private readonly string _root;

    public RazorIncrementalDeclineTests()
    {
        _root = Path.Combine(Path.GetTempPath(), "csmesh-razor-inc-" + Guid.NewGuid().ToString("N")[..8]);
        Directory.CreateDirectory(Path.Combine(_root, "Pages"));

        Write("App.csproj",
            "<Project Sdk=\"Microsoft.NET.Sdk.Web\"><PropertyGroup><TargetFramework>net10.0</TargetFramework></PropertyGroup></Project>");
        Write("Pages/Counter.razor", "<h1>@currentCount</h1>");

        var generatedDir = Path.Combine(_root, "obj", "Debug", "net10.0", "generated",
            "Microsoft.CodeAnalysis.Razor.Compiler",
            "Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator", "Pages");
        Directory.CreateDirectory(generatedDir);

        var razorPath = Path.Combine(_root, "Pages", "Counter.razor").Replace('\\', '/');
        File.WriteAllText(Path.Combine(generatedDir, "Counter_razor.g.cs"), $$"""
            #pragma checksum "{{razorPath}}" "{ff1816ec-aa5e-4d10-87f6-980198115c8b}" "0000"
            namespace TestApp.Pages
            {
                public partial class Counter : global::Microsoft.AspNetCore.Components.ComponentBase
                {
                }
            }
            """);
    }

    private void Write(string relative, string content)
    {
        var path = Path.Combine(_root, relative.Replace('/', Path.DirectorySeparatorChar));
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        File.WriteAllText(path, content);
    }

    [Fact]
    public void EditingTheRazorFileDeclinesTheIncrementalPass()
    {
        var before = Indexer.Build(_root);
        Assert.Equal(1, before.RazorComponentsIndexed);

        // A size change alone is enough to make DirtyFiles report it regardless of mtime
        // resolution -- no sleep needed to clear the tolerance window.
        File.WriteAllText(Path.Combine(_root, "Pages", "Counter.razor"),
            "<h1>@currentCount</h1>\n<p>edited, quite a bit longer now</p>");

        var dirty = GraphStore.DirtyFiles(before);
        Assert.Contains(Path.Combine("Pages", "Counter.razor"), dirty);

        Assert.Null(Indexer.BuildIncremental(before, dirty));
    }

    public void Dispose()
    {
        try { Directory.Delete(_root, recursive: true); } catch { /* temp dir */ }
    }
}

/// <summary>'doctor' is the only place an agent learns whether Razor components actually made it in.</summary>
[Collection("console-capture")]
public sealed class RazorDoctorGeneratedSourceTests : IDisposable
{
    private readonly string _root;

    public RazorDoctorGeneratedSourceTests()
    {
        _root = Path.Combine(Path.GetTempPath(), "csmesh-razor-doctor2-" + Guid.NewGuid().ToString("N")[..8]);
        Directory.CreateDirectory(Path.Combine(_root, "Pages"));

        Write("App.csproj",
            "<Project Sdk=\"Microsoft.NET.Sdk.Web\"><PropertyGroup><TargetFramework>net10.0</TargetFramework></PropertyGroup></Project>");
        Write("Pages/Counter.razor", "<h1>@currentCount</h1>");
    }

    private void Write(string relative, string content)
    {
        var path = Path.Combine(_root, relative.Replace('/', Path.DirectorySeparatorChar));
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        File.WriteAllText(path, content);
    }

    private void WriteGeneratedComponent()
    {
        var generatedDir = Path.Combine(_root, "obj", "Debug", "net10.0", "generated",
            "Microsoft.CodeAnalysis.Razor.Compiler",
            "Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator", "Pages");
        Directory.CreateDirectory(generatedDir);

        var razorPath = Path.Combine(_root, "Pages", "Counter.razor").Replace('\\', '/');
        File.WriteAllText(Path.Combine(generatedDir, "Counter_razor.g.cs"), $$"""
            #pragma checksum "{{razorPath}}" "{ff1816ec-aa5e-4d10-87f6-980198115c8b}" "0000"
            namespace TestApp.Pages
            {
                public partial class Counter : global::Microsoft.AspNetCore.Components.ComponentBase { }
            }
            """);
    }

    private static string Capture(Func<int> run)
    {
        var original = Console.Out;
        var buffer = new StringWriter();
        try
        {
            Console.SetOut(buffer);
            run();
        }
        finally
        {
            Console.SetOut(original);
        }

        return buffer.ToString();
    }

    [Fact]
    public void DoctorNamesTheBuildCommandWhenNoGeneratedOutputWasFound()
    {
        IndexCommand.Execute(_root, new Options([]));

        var raw = Capture(() => DoctorCommand.Execute(_root, new Options([])));

        Assert.Contains("dotnet build --no-incremental -p:EmitCompilerGeneratedFiles=true", raw, StringComparison.Ordinal);
    }

    [Fact]
    public void DoctorReportsHowManyComponentsWereIndexedWhenGeneratedOutputIsPresent()
    {
        WriteGeneratedComponent();
        IndexCommand.Execute(_root, new Options([]));

        var raw = Capture(() => DoctorCommand.Execute(_root, new Options([])));

        Assert.Contains("1 of 1 .razor/.cshtml file(s)", raw, StringComparison.Ordinal);
        Assert.DoesNotContain("dotnet build --no-incremental", raw, StringComparison.Ordinal);
    }

    public void Dispose()
    {
        try { Directory.Delete(_root, recursive: true); } catch { /* temp dir */ }
    }
}
